-- Ejecuta este script en el SQL Editor de tu proyecto Supabase para crear la tabla de auditoría

CREATE TABLE incident_logs (
    id bigint generated by default as identity primary key,
    incident_id bigint references incidents(id) on delete set null,
    user_id text,
    user_name text,
    action text not null, -- 'CREAR', 'MODIFICAR', 'ELIMINAR'
    incident_data jsonb,
    previous_data jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE incident_logs ENABLE ROW LEVEL SECURITY;

-- Política de lectura: Permitir lectura (la UI ya lo restringe a Administradores)
CREATE POLICY "Permitir lectura a todos los autenticados" ON incident_logs
  FOR SELECT USING (true);

-- Política de inserción: Permitir que cualquier usuario autenticado guarde logs de sus acciones
CREATE POLICY "Permitir inserción a todos" ON incident_logs
  FOR INSERT WITH CHECK (true);
